### ISSUE TITLE
Add a hint on deploying a vnode using an existing kernel/image

### ISSUE THREAD

**Issue by ghost** [InfraSIM/docs#11]
CirrOS for example?

My concern is that building the kernel is a long duration process.  Perhaps the kernels for this could be packaged / repoed so they don't need to be built regularly.

**Comment by fub2** [comment]
https://github.com/InfraSIM/infrasim-compute could eliminate effort building kernel and entire file system. But it is current requiring to run it on top of Ubuntu 16.04 (we tested and daily development based on it).

https://github.com/InfraSIM/idic does requires building kernel and entire filesystem and ultimately build one virtual machine template.

So in summary, it not very easy and straitforward to port virtual node implementation around. At least first step is to make sure new platform is able to build and run openipmi and qemu (2 another repo under infrasim project).
